### ISSUE TITLE
[bug] Name resolver error: produced zero addresses

### ISSUE THREAD

**Issue by cubic3d** [jfroy/tnu#3]
Hey, thanks for this little helper! I'm running into issues here:

```
waiting for etcd to be healthy: ...
waiting for etcd to be healthy: OK
waiting for etcd members to be consistent across nodes: ...
waiting for etcd members to be consistent across nodes: OK
waiting for etcd members to be control plane nodes: ...
waiting for etcd members to be control plane nodes: OK
waiting for apid to be ready: ...
waiting for apid to be ready: OK
waiting for all nodes memory sizes: ...
waiting for all nodes memory sizes: OK
waiting for all nodes disk sizes: ...
waiting for all nodes disk sizes: OK
waiting for no diagnostics: ...
waiting for no diagnostics: OK
waiting for kubelet to be healthy: ...
waiting for kubelet to be healthy: OK
waiting for all nodes to finish boot sequence: ...
waiting for all nodes to finish boot sequence: OK
waiting for all k8s nodes to report: ...
waiting for all k8s nodes to report: OK
waiting for all control plane static pods to be running: ...
waiting for all control plane static pods to be running: OK
waiting for all control plane components to be ready: ...
waiting for all control plane components to be ready: OK
waiting for all k8s nodes to report ready: ...
waiting for all k8s nodes to report ready: OK
waiting for kube-proxy to report ready: ...
waiting for kube-proxy to report ready: SKIP
waiting for coredns to report ready: ...
waiting for coredns to report ready: OK
waiting for all k8s nodes to report schedulable: ...
waiting for all k8s nodes to report schedulable: OK
panic: rpc error: code = Unavailable desc = name resolver error: produced zero addresses

goroutine 1 [running]:
main.main()
        tnu/tnu.go:55 +0xda9
```

using the following Plan:
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  version: ${TALOS_VERSION}
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true

  concurrency: 1
  exclusive: true

  nodeSelector:
    matchExpressions:
      - key: feature.node.kubernetes.io/system-os_release.ID
        operator: In
        values:
          - talos

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  prepare:
    image: ghcr.io/siderolabs/talosctl:${TALOS_VERSION}

    envs: &envs
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

    args:
      - --nodes=$(NODE)
      - health
      - --server=false

  upgrade:
    image: ghcr.io/jfroy/tnu:0.2.1

    envs: *envs

    args:
      - --node=$(NODE)
      - --tag=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
```

The prepare container exits fine using the node name, but tnu seems to panic at
https://github.com/jfroy/tnu/blob/efc35d2f81175f0898620b288230602c8178f16c/tnu.go#L53

If I try to request the resource manually from talosctl: `talosctl --nodes=akane get nodenames.kubernetes.talos.dev` I get the error from the panic: `rpc error: code = Unavailable desc = name resolver error: produced zero addresses`.

My nodes are defined using a FQDN, e.g. `akane.h.example.com` using `talosctl --nodes=akane.h.example.com get nodenames.kubernetes.talos.dev` is successful:
```
NODE                  NAMESPACE   TYPE       ID         VERSION   NODENAME
akane.h.example.com   k8s         Nodename   nodename   1         akane
```

But if I now change the `--node` parameter of tnu to match that, it fails with the following message: `expected node akane.h.example.com, got akane`, because the node name is still akane. `spec.nodeName` of the Pod is set to `akane` as well by the k8s controller.
